version: '2'
services:
  nginx:
    image: nginx:1.11.5-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/usr/share/nginx/html/
    links:
      - socket
    ports:
      - 80:80
    tty: true
    command: nginx -g 'daemon off;'

  socket:
    image: node:7.5.0-alpine
    volumes:
      - ./node/:/mnt
    working_dir: /mnt
    tty: true
    command: node index.js
